# Locators pour la page d'accueil et la page de login
HOME_URL = "https://automationplayground.com/crm/index.html"
LOGIN_LINK = "link:Sign In"
LOGOUT_LINK = "xpath://a[contains(text(), 'Sign Out')]"
EMAIL_INPUT = "id:email-id"
PASSWORD_INPUT = "id:password"
SUBMIT_BUTTON = "id:submit-id"
PAGE_TEXT = "xpath://h2[contains(text(), 'Customers Are Priority One!')]"
CUSTOMER_PAGE_TEXT = "xpath://h2[contains(text(), 'Our Happy Customers')]"
REMEMBER_ME_CHECKBOX = "id:remember"
CUSTOMERS_GRID = "xpath://table[@id='customers']//tbody/tr"
ADD_CUSTOMER_BUTTON = "id:new-customer"
EMAIL_INPUT_ADD = "id:EmailAddress"
FIRST_NAME_INPUT = "id:FirstName"
LAST_NAME_INPUT = "id:LastName"
CITY_INPUT = "id:City"
STATE_INPUT = "id:StateOrRegion"
GENDER_RADIO_MALE = "xpath://*[@id='loginform']/div/div/div/div/form/div[6]/input[1]"
GENDER_RADIO_FEMALE = "xpath://*[@id='loginform']/div/div/div/div/form/div[6]/input[2]"
SAVE_BUTTON = "xpath://*[@id='loginform']/div/div/div/div/form/button"
PROMOTIONNAL_CHECKBOX = "xpath:/html/body/section/div/div/div/div/form/div[7]/input"
ADD_CUSTOMER_PAGE_TEXT = "xpath://h2[contains(text(), 'Add Customer')]"
CANCEL_BUTTON = "//a[contains(@class, 'btn') and contains(@class, 'btn-default') and text()='Cancel']"